@startuml

!theme plain
top to bottom direction
skinparam linetype polyline

class node46 as "' ~ theme_github_banner, resource=True) }}"
class node55 as "' ~ theme_logo, 1) }}"
class node15 as "' ~ theme_touch_icon, resource=True) }}"
class node0 as "agogo/layout.html"
class node29 as "alabaster/about.html"
class node7 as "alabaster/donate.html"
class node40 as "alabaster/layout.html"
class node31 as "basic/domainindex.html"
class node1 as "basic/layout.html"
class node57 as "basic/search.html"
class node24 as "bizstyle.js', 1) }}"
class node39 as "bizstyle/layout.html"
class node54 as "button.png?color={{ theme_opencollective_button_color }}"
class node12 as "changes/versionchanges.html"
class node47 as "classic/layout.html"
class node16 as "coverage.svg?branch={{ theme_badge_branch }}"
class node13 as "css?family=Neuton&amp;subset=latin"
class node14 as "css?family=Nobile:regular,italic,bold,bolditalic&amp;subset=latin"
class node21 as "custom.css', resource=True) }}"
class node38 as "default.css"
class node3 as "default/framing.css"
class node37 as "default/pretty.css"
class node56 as "default/s5-core.css"
class node22 as "default/slides.css"
class node6 as "donate-%E2%9D%A4%C2%A0-ff69b4.svg?style=flat"
class node33 as "epub/epub-cover.html"
class node30 as "github-banner.svg', resource=True) }}"
class node41 as "haiku/layout.html"
class node44 as "js?id={{ theme_analytics_id }}"
class node18 as "language_data.js', 1) }}"
class node28 as "minus.png', 1) }}"
class node58 as "opensearch.xml', 1) }}"
class node50 as "print.css"
class node5 as "pyramid/layout.html"
class node25 as "scrolls/layout.html"
class node42 as "searchtools.js', 1) }}"
class node34 as "sidebar.js', 1) }}"
class node52 as "sphinx_rtd_theme/layout.html"
class node8 as "sphinx_rtd_theme/search.html"
class node48 as "theme.js', 1) }}"
class node51 as "theme_extras.js', 1) }}"
class node36 as "versions.js', 1) }}"
class node45 as "{{ _logo_url }}"
class node32 as "{{ favicon_url }}"
class node20 as "{{ favicon_url|e }}"
class node23 as "{{ image }}"
class node10 as "{{ logo_url|e }}"
class node11 as "{{ next.link|e }}"
class node27 as "{{ pageurl|e }}"
class node26 as "{{ path }}.svg?branch={{ theme_badge_branch }}"
class node2 as "{{ pathto('about') }}"
class node35 as "{{ pathto('copyright') }}"
class node17 as "{{ pathto('genindex') }}"
class node49 as "{{ pathto('search') }}"
class node9 as "{{ pathto('searchindex.js', 1) }}"
class node19 as "{{ pathto(css, 1)|e }}"
class node43 as "{{ pathto(css_file, 1)|escape }}"
class node53 as "{{ prev.link|e }}"
class node4 as "{{ theme_canonical_url }}{{ pagename }}.html"

node0   <-[#595959,plain]-  node10 
node29  <-[#595959,plain]-  node55 
node29  <-[#595959,plain]-  node16 
node29  <-[#595959,plain]-  node26 
node7   <-[#595959,plain]-  node54 
node7   <-[#595959,plain]-  node6  
node40  <-[#595959,plain]-  node46 
node40  <-[#595959,plain]-  node15 
node40  <-[#595959,plain]-  node21 
node40  <-[#595959,plain]-  node30 
node40  <-[#595959,plain]-  node4  
node31  <-[#595959,plain]-  node28 
node1   <-[#595959,plain]-  node58 
node1   <-[#595959,plain]-  node20 
node1   <-[#595959,plain]-  node10 
node1   <-[#595959,plain]-  node11 
node1   <-[#595959,plain]-  node27 
node1   <-[#595959,plain]-  node2  
node1   <-[#595959,plain]-  node35 
node1   <-[#595959,plain]-  node17 
node1   <-[#595959,plain]-  node49 
node1   <-[#595959,plain]-  node19 
node1   <-[#595959,plain]-  node53 
node57  <-[#595959,plain]-  node18 
node57  <-[#595959,plain]-  node42 
node57  <-[#595959,plain]-  node9  
node39  <-[#595959,plain]-  node24 
node12  <-[#595959,plain]-  node38 
node47  <-[#595959,plain]-  node34 
node22  <-[#595959,plain]-  node3  
node22  <-[#595959,plain]-  node37 
node22  <-[#595959,plain]-  node56 
node33  <-[#595959,plain]-  node23 
node41  <-[#595959,plain]-  node10 
node5   <-[#595959,plain]-  node13 
node5   <-[#595959,plain]-  node14 
node5   <-[#595959,plain]-  node10 
node25  <-[#595959,plain]-  node50 
node25  <-[#595959,plain]-  node51 
node52  <-[#595959,plain]-  node44 
node52  <-[#595959,plain]-  node58 
node52  <-[#595959,plain]-  node48 
node52  <-[#595959,plain]-  node36 
node52  <-[#595959,plain]-  node45 
node52  <-[#595959,plain]-  node32 
node52  <-[#595959,plain]-  node11 
node52  <-[#595959,plain]-  node27 
node52  <-[#595959,plain]-  node2  
node52  <-[#595959,plain]-  node35 
node52  <-[#595959,plain]-  node17 
node52  <-[#595959,plain]-  node49 
node52  <-[#595959,plain]-  node43 
node52  <-[#595959,plain]-  node53 
node52  <-[#595959,plain]-  node4  
node8   <-[#595959,plain]-  node18 
node8   <-[#595959,plain]-  node42 
@enduml
